server:
  port: 9000

spring:
  redis:
      host: 10.11.146.231
      port: 6379
      password: aN3eg2Ak@
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  application:
    name: mail-server